
INSERT
INTO tr_project(
 id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
 pic_name, mic_name, opportunity_id,
 opportunity_name,opportunity_source, is_contingent_basis,
 profit_ctr, engagement_desc, open_code_date,
 start_date, close_date, location,
 lcsp, region_code, service_offering,
 service_offering_desc, func_service_line, scope_of_service,
 est_Fee, eng_letter_no, is_recurring,engagement_risk,
 confidentiality_risk, industry_code, industry,dtt_relationship,
 client_risk, type_of_client, nature_of_business,
 master_code, cea_status, service_item_team_member,
 cea_approval_date, primary_address, city,
 year_end_month,business_registration_no, country, province
)
VALUES(
 NEWID(), 0, 'FA', 
 '021-010', '1000010', 'CC010', 'MIC001-021', 'US', '2020', '100240', '100590', 'true', 
 'Guo Juan', 'Xiang Kuan', '3000001017', 
 'BVI Insolvent Liquidation', 'Client referral', 'No',
 '3NG000', 'HKRS161-BVI Insolvent Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'GDC', 'FVM', 
 'V&M RCV-COMPLIANCE VALUATION', 'FAS', 'One partner of Deloitte China and one BVI Insolvency Practitioner will act as joint and several liquidators of the clients in insolvent liquidation.',
 234000.00, 'EL16HKFAS0081', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK'
)
INSERT INTO tr_project(
id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-011', '1000011', 'CC011', 'MIC001-011', 'US', '2020', '100240', '100590', 'true',
	'Guo Juan', 'Xiang Kuan', '3000030100', 
 'BVI Insolvent Liquidation', 'Existing client', 'No',
 '3NG000', 'GZRA161-GZE- Project Titan2-GZ','2019-01-15', 
 '2018-08-24', '2019-07-31', 'GZ',  
 '911007', 'GDC', 'FVM', 
 'V&M RCV-FIN RPT VAL (BIZ VAL)', 'FAS', 'One partner of Deloitte China and one BVI Insolvency Practitioner will act as joint and several liquidators of the clients in insolvent liquidation.',
 2500000.00, 'EL16GZFAS0007', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Investment holdings', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK'
 )

INSERT INTO tr_project(
id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-012', '1000012', 'CC012', 'MIC001-012', 'US', '2020', '100240', '100590', 'true',
	'Guo Juan', 'Xiang Kuan', '3000152901', 
 'GZE- Project Titan2-GZ + HK', 'Internal development', 'Yes',
 '3NG000', 'SHCA162-Project Avus&Libra(Success Fee)','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SH',  
 '911007', 'GDC', 'FVM', 
 'V&M RCV-FIN RPT VAL (FIN INST)', 'FAS', '? Assist client in understanding the business and financial status of  the target company;@@@? Assist client in working with the target (and its advisors)/other stakeholders in the formulation of an appropriate restructuring plan; and@@@? Provide support to the client in its (the client) discussion with other stakeholders of the target company in the finalization and implementation of the restructuring plan@@@',
 10000000.00, 'EL16SHFAS0362', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', '', 
 'Corporation', 'trading of oil product, metal and petrochemicals products', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(
id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-013', '1000013', 'CC013', 'MIC001-013', 'US', '2020', '100240', '100590', 'true',
	'Guo Juan', 'Xiang Kuan', '3000041832', 
 'Assist the client in acquiring an European metal recycling company', 'Walk-in', 'Yes',
 '3NG000', 'BXCA161-FUND RAISING- Success fee','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '911007', 'GDC', 'FVM', 
 'V&M RCV-PORTFOLIO VAL SERVICES', 'FAS', 'buyside financial advisory service',
.90, 'EL16BJFAS0165', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'The company''s mission is to build up core business platform for renewable resources in China through strategic acquisition and investment.  Main business includes renewable resource recycling, energy-saving high-technology and related logistics.', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(
id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-014', '1000014', 'CC014', 'MIC001-014', 'US', '2020', '100240', '100590', 'true',
	'Guo Juan', 'Xiang Kuan', '3000152901', 
 'Zhaoheng', 'SHRA161-Liquidation advisory', 'No',
 '3NG000', 'HKRS161-BVI Insolvent Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SH',  
 '911007', 'GDC', 'FVM', 
 'V&M RCV-TAX VALUATION', 'FAS', 'Our mandate is to raise capital for a new subsidiary to be set up by the injection of a portfolio of operating hydropower plants.  @@@Our proposed scope of work include the following:@@@? Assist the Client to identify a portfolio to be injected from current hydropower plants;@@@? Assist the Client to execute carve-out process;@@@? Assist  the Client to identify and initiate initial contact with the potential investors; @@@? Assist the Client to prepare marketing material to the potential investor(s); @@@? Attend meetings with potential investors as requested by the Client;@@@? Advise the Client on the conduct of negotiations with potential investor(s); and@@@? Assist the Client in liaising with varif the relevant agreement.@@@',
 1600000.00, 'EL16SHFAS0201', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', '', 
 'Corporation', 'Public Company', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(
id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-015', '1000015', 'CC015', 'MIC001-015', 'US', '2020', '100240', '100590', 'true',
	'Guo Juan', 'Xiang Kuan', '3000139068', 
 'Toshiba Materials', 'Client referral', 'No',
 '3NG000', 'SHRA161-Liquidation advisory','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '911007', 'GDC', 'FVM', 
 'V&M TVA-CORP DEVELOP SERVICES', 'FAS', '1. Advise on key points for facilitating client to negotiate with Chinese Partner which is Target''s minority shareholder@@@2. Conduct pre-liquidation analysis@@@3. Advise and assist in drafting liquidation work plan and roadmap @@@4. Advise on liquidation procedures (if client requests) @@@',
 100000.00, 'EL17BJFAS0034', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Development, manufacturing and sales of Fine Ceramics, Applied Phosphor Products, High-purity Metals, Magnetic Parts, Tungsten and Molybdenum, Special Metals and Alloys and other application products. @@@', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(
id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-016', '1000016', 'CC016', 'MIC001-016', 'US', '2020', '100240', '100590', 'true',
	'Guo Juan', 'Xiang Kuan', '3000160953', 
 '��������', 'BXVT171-Ext - �������ݻ���', 'No',
 '3NG000', 'HKRS161-BVI Insolvent Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'NJ',  
 '911007', 'GDC', 'FVM', 
 'V&M TVA-FAIRNESS OPINIONS', 'FAS', 'We will provide fund portfolio valuation service on a monthly basis.',
 104000.00, 'EL17SHFAS0081', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Partnership', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(
id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-017', '1000017', 'CC017', 'MIC001-017', 'US', '2020', '100240', '100590', 'true',
	'Guo Juan', 'Xiang Kuan', '3000160130', 
 'Project Crystal - financial and tax due diligence', 'Client referral', 'No',
 '3NG000', 'SHCT171-Project Crystal- FDD&TDD','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'GDC', 'FVM', 
 'V&M TVA-INTELLECTUAL PROPERTY VAL', 'FAS', 'FDD and TDD',
 1249000.00, 'EL17BJFAS0071', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', '', 
 'Corporation', 'Investment in new tech/new material/internet business.', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-018', '1000018', 'CC018', 'MIC001-018', 'US', '2020', '100240', '100590', 'true',
	'Guo Juan', 'Xiang Kuan', '3000186164', 
 'Financial Review and Debt Restructuring Advisory', 'Internal development', 'No',
 '3NG000', 'BXRA171-BJ Master-retainer','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'GDC', 'FVM', 
 'V&M LCV-LITIGATION & CONTENTIOUS VAL', 'FAS', '1. Perform limited scope financial review on the target group;@@@2. Assist the client in fomulating debt restructuring plan;',
 675000.00, 'EL17SHFAS0472', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', '', 
 'Corporation', 'Bank', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-019', '1000019', 'CC019', 'MIC001-019', 'US', '2020', '100240', '100590', 'true',
	'Guo Juan', 'Xiang Kuan', '3000152901', 
 'Project Great', 'Existing client', 'No',
 '3NG000', 'NJCT181-FDD-NJ New','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'GDC', 'FVM', 
 'V&M MDL-STRA VAL & FIN MDL', 'FAS', 'FDD&TDD',
 1.00, 'EL17HKFAS0054', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Logistics services', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')



INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-020', '1000020', 'CC020', 'MIC001-020', 'US', '2020', '100244', '100816', 'true',
	'Yi Sheng', 'Rena', '3000173114', 
 'MVL', 'Deloitte member firm referral', 'Yes',
 '3NG000', 'HKRS171-Court liquidation-HKRS171 (Maste','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '911007', 'GDC', 'FVM', 
 'V&M CAA-CAPITAL ASSET ADVISORY', 'FAS', '1. The client is a company incorporated in Hong Kong. @@@2. It engages in manufacturing and retailing shoes business.@@@3. This case is a court appointed liquidation case.@@@4. As appointed by the court, Mr Derek lai and Mr Glen Ho will act as liquidators of the Client',
 12000000.00, 'EL17HKFAS0221', 'Y',
 'Normal', 'Medium', 'FZZ0', 
 'Financial Services Industry', 'No', 'Greater Than Normal', 
 'Corporation', 'Manufacturing and retailing of children''s shoes', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-021', '1000021', 'CC021', 'MIC001-021', 'US', '2020', '100244', '100816', 'true',
	'Yi Sheng', 'Rena', '3000150208', 
 'Project Heaven', 'Staff referral', 'No',
 '3NG000', 'HKCA171-Project AMT_NRA','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'GDC', 'FVM', 
 'V&M MDL-PPP/I&CP ADVISORY', 'FAS', 'To assist in the Client''s fund raising by means of issuing new equity@@@? Assist  the Client to identify and initiate initial contact with the potential investors; @@@? Attend meetings with potential investors as requested by the Client. (subject to prior notice and our availability);@@@? Advise the Client  during the negotiations with potential investor(s);@@@? Assist the client on the evaluation of initial proposals by potential investors in relation to the Client''s fund raising@@@? Assist the Client in liaising with various parties to ensure timely execution of the relevant agreement.@@@',
 125000.00, 'EL17HKFAS0289', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Greater Than Normal', 
 'Corporation', 'Manufactoring of High-technique memory', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-022', '1000022', 'CC022', 'MIC001-022', 'US', '2020', '100244', '100816', 'true',
	'Yi Sheng', 'Rena', '3000030100', 
 'Project Dongfeng', 'Existing client', 'No',
 '3NG000', 'HKRS171-Creditors Voluntary Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SH',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-AUDIT REVIEW SUPPORT', 'FAS', 'To act as liquidators for the client. The proposed liquidation of the client is part of the restructuring plan of its parent company,  CECEP COSTIN New Materials Group Limited ("CECEP COSTIN")@@@',
 219870.00, 'EL17HKFAS0286', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Trading of non-woven fabrics and other types of non-woven materials', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-023', '1000023', 'CC023', 'MIC001-023', 'US', '2020', '100244', '100816', 'true',
	'Yi Sheng', 'Rena', '3000149865', 
 'Baha Mar Project', 'Staff referral', 'No',
 '314060', 'BXCT171-FDD and SPA review for ChemChina','2019-01-15', 
 '2018-08-24', '2019-07-31', 'NJ',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-COMPLIANCE VALUATION', 'FAS', 'Provide financial due diligence and SPA review service to client',
 18000.00, 'EL17HKFAS0195', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', '', 
 'Corporation', 'Petrochemical', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-024', '1000024', 'CC024', 'MIC001-024', 'US', '2020', '100244', '100816', 'true',
 'Yi Sheng', 'Rena', '3000160130', 
 'Court Liquidation', 'Staff referral', 'No',
 '314060', 'HKRS171-Members Voluntary Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-FIN RPT VAL (BIZ VAL)', 'FAS', 'This is MVL case, 2 Partners will act as Joint and Several Liquidators of the company.',
 950000.00, 'EL17SHFAS0334', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', '', 
 'Corporation', 'Private holding company', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-025', '1000025', 'CC025', 'MIC001-025', 'US', '2020', '100244', '100816', 'true',
	'Yi Sheng', 'Rena', '3000096717', 
 'Baha Mar Project', 'Staff referral', 'No',
 '314060', 'SHDT171-Market Study','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-FIN RPT VAL (FIN INST)', 'FAS', 'Financial Due Diligence and Tax Due Diligence',
 631296.00, 'EL18SHFAS0057', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Others', 'Public Sector', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-026', '1000026', 'CC026', 'MIC001-026', 'US', '2020', '100244', '100816', 'true',
	'Yi Sheng', 'Rena', '3000138074', 
 'Court Liquidation', 'Walk-in', 'No',
 '314060', 'NJCT181-FDD-NJ','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-PORTFOLIO VAL SERVICES', 'FAS', '',
 256410.26, 'EL17HKFAS0296', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', '', 
 'Partnership', 'PE', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-027', '1000027', 'CC027', 'MIC001-027', 'US', '2020', '100244', '100816', 'true',
	'Yi Sheng', 'Rena', '3000097644', 
 'Baha Mar Project', 'BXRA181-Baha Mar Project (BXRA181)', 'No',
 '314060', 'HKRS161-BVI Insolvent Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-TAX VALUATION', 'FAS', '',
 50000.00, 'EL16HKFAS0187', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', '', 
 'Corporation', '����׼������Ϲ��Ҷ���ó�׺͡��߳�ȥ������Ķ��ڡ����ںͳ��ڴ���,�������Ŵ��������Ŵ�������а����̴������Ͷ�ʴ���й�����Ԯ���Żݴ�����Żݳ������Ŵ���;�������Ժָ�������ִ���;������������͹��ʽ��ڻ���ת����(ת����)ҵ���е�������Ŀ����������״���;�������ſͻ����´��;���н���ծȯ;������������ͽ��ۻ�ҵ��;������������֤������͢��������ʽ��ó������ҵ��;���������ó����ص�ί�д���ҵ��;���������ó����صĵ���ҵ��;������׼�����ҵ��;���������������ͳ���ծȯ;����ͬҵ��衢���ҵ��;���������ҵ����ص����ŵ��顢��ѯ����������֤ҵ��;����Ʊ�ݳж�������;�����ո����������ҵ��;������������������������Ʒ;�ʲ�֤ȯ��ҵ��;��ҵ������ʷ���;��֯��μ����Ŵ���;�����֧�����ڽ�����������Ȩ��Χ�ھ�Ӫ���ط�����ɵ�����ҵ��;��������׼�����ӹ�˾��ʽ��չ��ȨͶ�ʼ�����ҵ��;������Ժ����ҵ�ල���������׼������ҵ��(��ҵ��������ѡ��Ӫ��Ŀ,��չ��Ӫ�;�����뾭��׼����Ŀ,����ز�����׼������׼�����ݿ�չ��Ӫ�;���ô��±��в�ҵ���߽�ֹ����������Ŀ�ľ�Ӫ���)', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-028', '1000028', 'CC028', 'MIC001-028', 'US', '2020', '100244', '100816', 'true',
	'Yi Sheng', 'Rena', '3000062314', 
 'Court Liquidation', 'Existing client', 'No',
 '314060', 'HKRA162-Court Liquidation (HKRA162)','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SZ',  
 '911007', 'SCHK', 'FVM', 
 'V&M TVA-CORP DEVELOP SERVICES', 'FAS', '',
 1.00, 'EL17HKFAS0296', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', '', 
 'Corporation', 'n/a', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-029', '1000029', 'CC029', 'MIC001-029', 'US', '2020', '100244', '100816', 'true',
	'Yi Sheng', 'Rena', '3000070893', 
 'Baha Mar Project', 'Existing client', 'No',
 '314060', 'HKRS182-Baha Mar Project (HKRS182)','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SZ',  
 '911007', 'SCHK', 'FVM', 
 'V&M TVA-FAIRNESS OPINIONS', 'FAS', '',
 200000.00, 'EL17HKFAS0289', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', '����׼������Ϲ��Ҷ���ó�׺͡��߳�ȥ������Ķ��ڡ����ںͳ��ڴ���,�������Ŵ��������Ŵ�������а����̴������Ͷ�ʴ���й�����Ԯ���Żݴ�����Żݳ������Ŵ���;�������Ժָ�������ִ���;������������͹��ʽ��ڻ���ת����(ת����)ҵ���е�������Ŀ����������״���;�������ſͻ����´��;���н���ծȯ;������������ͽ��ۻ�ҵ��;������������֤������͢��������ʽ��ó������ҵ��;���������ó����ص�ί�д���ҵ��;���������ó����صĵ���ҵ��;������׼�����ҵ��;���������������ͳ���ծȯ;����ͬҵ��衢���ҵ��;���������ҵ����ص����ŵ��顢��ѯ����������֤ҵ��;����Ʊ�ݳж�������;�����ո����������ҵ��;������������������������Ʒ;�ʲ�֤ȯ��ҵ��;��ҵ������ʷ���;��֯��μ����Ŵ���;�����֧�����ڽ�����������Ȩ��Χ�ھ�Ӫ���ط�����ɵ�����ҵ��;��������׼�����ӹ�˾��ʽ��չ��ȨͶ�ʼ�����ҵ��;������Ժ����ҵ�ල���������׼������ҵ��(��ҵ��������ѡ��Ӫ��Ŀ,��չ��Ӫ�;�����뾭��׼����Ŀ,����ز�����׼������׼�����ݿ�չ��Ӫ�;���ô��±��в�ҵ���߽�ֹ����������Ŀ�ľ�Ӫ���)', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')



INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-030', '1000030', 'CC030', 'MIC001-030', 'US', '2020', '100308', '101006', 'true',
	'Guo Juan', 'Xiang Kuan', '3000150279', 
 'CVL', 'Existing client', 'No',
 '314060', 'BXRA171-Creditors Voluntary Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'FVM', 
 'V&M TVA-INTELLECTUAL PROPERTY VAL', 'FAS', '',
 44000.00, 'EL18HKFAS0015', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Trading of non-woven fabrics and other types of non-woven materials', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-031', '1000031', 'CC031', 'MIC001-031', 'US', '2020', '100308', '101006', 'true',
	'Jian', 'Xiang Kuan', '3000138074', 
 'Project Channel', 'Walk-in', 'No',
 '314060', 'SZCT181-FDD - SZ - LAW/CHCW','2019-01-15', 
 '2018-08-24', '2019-07-31', 'GZ',  
 '911007', 'SCHK', 'ROA', 
 'V&M LCV-LITIGATION & CONTENTIOUS VAL', 'FAS', '',
 3500000.00, 'EL17HKFAS0400', 'N',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-032', '1000032', 'CC032', 'MIC001-032', 'US', '2020', '100308', '101006', 'true',
	'Jian', 'Xiang Kuan', '3000154286', 
 'Creditors Voluntary Liquidation', 'Others', 'No',
 '314060', 'SZRA181-Creditors Voluntary Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SH',  
 '911007', 'SCHK', 'ROA', 
 'V&M MDL-STRA VAL & FIN MDL', 'FAS', '',
 197000.00, 'EL18HKFAS0068', 'N',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-033', '1000033', 'CC033', 'MIC001-033', 'US', '2020', '100308', '101006', 'true',
	'Jian', 'Xiang Kuan', '3000136232', 
 'Project-Gaia ', 'Existing client', 'No',
 '314060', 'HKFT181-Project IQ-EDS/CY','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'ROA', 
 'V&M CAA-CAPITAL ASSET ADVISORY', 'FAS', '',
 256410.26, 'EL17HKFAS0296', 'N',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Telecom & Networking equipment.', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-034', '1000034', 'CC034', 'MIC001-034', 'US', '2020', '100308', '101006', 'true',
	'Jian', 'Xiang Kuan', '3000503394', 
 'Baha Mar Project', 'Existing client', 'No',
 '314060', 'GZRA181-Baha Mar Project (GZRA181)','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'ROA', 
 'V&M MDL-PPP/I&CP ADVISORY', 'FAS', '',
 250000.00, 'EL18SHFAS0057', 'N',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-035', '1000035', 'CC035', 'MIC001-035', 'US', '2020', '100308', '101006', 'true',
	'Jian', 'Xiang Kuan', '3000185905', 
 'Project Dongfeng', 'Walk-in', 'No',
 '314060', 'SHCT181-FDD-SH','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'NC', 'ROA', 
 'V&M RCV-AUDIT REVIEW SUPPORT', 'FAS', '',
 .10, 'EL17HKFAS0306', 'N',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-036', '1000036', 'CC036', 'MIC001-036', 'US', '2020', '100308', '101006', 'true',
	'Jian', 'Xiang Kuan', '3000096647', 
 'Project Newton', 'Walk-in', 'No',
 '314020', 'HKCA172-Financial Advisory and Fund Rais','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'NC', 'ROA', 
 'V&M RCV-COMPLIANCE VALUATION', 'FAS', '',
 625000.00, 'EL16GZFAS0007', 'N',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-037', '1000037', 'CC037', 'MIC001-037', 'US', '2020', '100308', '101006', 'true',
	'Jian', 'Xiang Kuan', '3000001017', 
 'GZE- Project Titan2-GZ + HK', 'Existing client', 'No',
 '314020', 'HKRA161-HK RA 1','2019-01-15', 
 '2018-08-24', '2019-07-31', 'NJ',  
 '911007', 'SCML', 'ROA', 
 'ROA-IA STRATEGY, EFFECTI ADV& RVW', 'FAS', '',
 130.00, 'EL17HKFAS0286', 'N',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-038', '1000038', 'CC038', 'MIC001-038', 'US', '2020', '100308', '101006', 'true',
	'Jian', 'Xiang Kuan', '3000001017', 
 'Project Cosmos', 'Staff referral', 'No',
 '326063', 'HKFT171-Provide FDD, TDD, SPA review and','2019-01-15', 
 '2018-08-24', '2019-07-31', 'GZ',  
 '116659', 'SCML', 'ROA', 
 'ROA-IA OUTSOURCING & CO-SOURCING', 'FAS', '',
 234000.00, 'EL17HKFAS0399', 'N',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-039', '1000039', 'CC039', 'MIC001-039', 'US', '2020', '100308', '101006', 'true',
	'Jian', 'Xiang Kuan', '3000001017', 
 'Creditors Voluntary Liquidation', 'Others', 'No',
 '326063', 'HKRA181-Creditors Voluntary Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '116659', 'SCML', 'ROA', 
 'ROA-US SOX READINESS', 'FAS', 'A. Project management assistance @@@B. Provide high-level advice in the implementation of accounts receivable (AR) transfer@@@C. Limited-scope high-level financial review',
 234000.00, 'EL17SHFAS0081', 'N',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')



INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-040', '1000040', 'CC040', 'MIC001-040', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 'Project Crystal - financial and tax due diligence', 'Client referral', 'No',
 '326063', 'NJCT171-FDD Nanjing','2019-01-15', 
 '2018-08-24', '2019-07-31', 'CD',  
 '116659', 'SCML', 'FVM', 
 'ROA-C-SOX READINESS', 'FAS', 'buy-side advisory service:  1.Conduct preliminary diagnosis of the target company; 2. due diligent on Target, financial modeling and purchase plan analysis;  3.Provide support on submission for approval and assist on transaction completion',
 234000.00, 'EL17BJFAS0274', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-041', '1000041', 'CC041', 'MIC001-041', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 'SE Potevio Mobile ', 'Marketing event', 'No',
 '326063', 'GZRA171-PJ building - GZ child code','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SH',  
 '116659', 'SCML', 'FVM', 
 'ROA-J-SOX READINESS', 'FAS', 'The propsed engagement includes services of1)financial due diligence 2)tax due diligence 3)tax structuring 4)valuation ',
 234000.00, 'EL17BJFAS0275', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-042', '1000042', 'CC042', 'MIC001-042', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 'Project Machine', 'Existing client', 'No',
 '326063', 'BXRA173-Pro Machine Phase 3','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SH',  
 '116659', 'SCML', 'FVM', 
 'ROA-INFORMATION TECH INTERNAL AUDIT', 'FAS', 'Support for liquidation preparation and execution ',
 234000.00, 'EL16CDFAS0019', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-043', '1000043', 'CC043', 'MIC001-043', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 'ɽ�����ټ��Ų������� - �򷽹��ʷ���', 'Existing client', 'No',
 '326063', 'CDCA161-Buy side advisory service for a','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '116659', 'SCML', 'FVM', 
 'ROA-INTERNAL AUDIT - LOAN STAFF SERVICES', 'FAS', 'A.Assistance in planning the Proposed Restructuring��?To coordinate with the legal counsel for advice and support to the Client in the considerations of overall process to obtain the Building Ownership Certificate for B1 Building from BHUCC; ?To comment on relevant documents and interview management from commercial and/or financial point of view; ?To coordinate with the legal counsel for advice in the consultation and communications with applicable government authorities to strive for you to obtain the Building Ownership Certificate directly from BHUCC.?To coordinate with the legal counsel for advice in the preparation of supplementary documents requested by the applicable government authorities.@@@B.Assistance in implementing the Proposed Restructuring?To coordinate with the legal counsel for advice in drafting and submitting the required documents to the government authorities;?To coordinate with the legal counsel for advice in handlingenquiries from the government authorities;',
 234000.00, 'EL16SHFAS0425', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-044', '1000044', 'CC044', 'MIC001-044', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 'Project Light -  financial due diligence, tax due diligence and valuation service', 'Staff referral', 'No',
 '326063', 'SHCT161-project light - financial due di','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '116659', 'SCML', 'FVM', 
 'ROA-INTERNAL CONTROL ADVISORY SERVICES', 'FAS', '- project management and coordination including: @@@?help to draft a project timetable; @@@?coordinate with all-party (including that at the seller & target side) to make sure the smooth progress of the project; @@@?help to deal with ad hoc issues related with project management@@@- negotiation support including: @@@?summarize key issues for negotiation regarding the potential restructuring;@@@?advise on negotiation strategy;@@@?assist on negotiation with the seller.',
 234000.00, 'EL18SHFAS0013', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-045', '1000045', 'CC045', 'MIC001-045', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 'Project Bearing', 'Others', 'No',
 '326063', 'SHRA181-PJ Bearing','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '116659', 'SCML', 'FVM', 
 'ROA-IPO & OTHER INTERNAL CONTROL DD SRV', 'FAS', 'We are engaged by �����µ¿�Ͷ�ʹ������޹�˾ ("Client") to provide Business Valuation for its 100% equity investment in a Commercial Aircraft company in the US. Our valuation report is solely used for Client''s internal management planning purposes��',
 234000.00, 'EL17BJFAS0274', 'Y',
 'Normal', 'Normal', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-046', '1000046', 'CC046', 'MIC001-046', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 'SE Potevio Mobile ', 'Marketing event', 'No',
 '326063', 'BXRA171-PJ building - BJ Master code','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '116659', 'SCHK', 'FVM', 
 'V&M RCV-AUDIT REVIEW SUPPORT', 'FAS', '',
 234000.00, 'EL17BJFAS0356', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-047', '1000047', 'CC047', 'MIC001-047', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 '������������ó�����޹�˾��ɽ��¥������ú�������޹�˾�����ʲ������չ�����ɽ��¥������ú�������޹�˾�ɶ��������ʹ�˾�Կ���Ŀ�깫˾�����ʲ�֮���������ѯ����', 'Existing client', 'No',
 '314060', 'BXRA171-Project T-BJ','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SH',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-COMPLIANCE VALUATION', 'FAS', '',
 234000.00, 'EL17BJFAS0168', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-048', '1000048', 'CC048', 'MIC001-048', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 'Project Sun', 'Staff referral', 'No',
 '314060', 'BXVT171-Project Sun','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-FIN RPT VAL (BIZ VAL)', 'FAS', '',
 234000.00, 'EL20HKFAS0082', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-049', '1000049', 'CC049', 'MIC001-049', 'US', '2020', '100318', '101016', 'true',
	'Jian', 'Xin', '3000001017', 
 'The Estate of Kwan Wai', 'Staff referral', 'No',
 '314060', 'HKRS131-Estate Administration Services','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-FIN RPT VAL (FIN INST)', 'FAS', '',
 234000.00, 'EL18SHFAS0093', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')



INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-050', '1000050', 'CC050', 'MIC001-050', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'Mark OReilly', 'Others', 'No',
 '314060', 'SHRA189-Liquidation advisory','2019-01-15', 
 '2018-08-24', '2019-07-31', 'GZ',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-PORTFOLIO VAL SERVICES', 'FAS', '',
 234000.00, 'EL17HKFAS0067', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-051', '1000051', 'CC051', 'MIC001-051', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'BVI Insolvent Liquidation', 'Client referral', 'No',
 '314060', 'SHRA189-Liquidation advisory','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SH',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-TAX VALUATION', 'FAS', '',
 234000.00, 'EL16HKFAS0081', 'Y',
 '', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-052', '1000052', 'CC052', 'MIC001-052', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'Project Channel', 'Existing client', 'No',
 '314060', 'HK7M171-Sundry of Mark OReilly','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '911007', 'SCHK', 'FVM', 
 'V&M TVA-CORP DEVELOP SERVICES', 'FAS', '',
 234000.00, 'EL16HKFAS0081', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-053', '1000053', 'CC053', 'MIC001-053', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'Project Dongfeng', 'Internal development', 'No',
 '314060', 'HKRS161-BVI Insolvent Liquidation','2019-01-15', 
 '2018-08-24', '2019-07-31', 'SH',  
 '911007', 'SCHK', 'FVM', 
 'V&M TVA-FAIRNESS OPINIONS', 'FAS', '',
 234000.00, 'EL16HKFAS0081', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-054', '1000054', 'CC054', 'MIC001-054', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'Toshiba Materials', 'Walk-in', 'No',
 '314060', 'GZRA161-GZE- Project Titan2-GZ','2019-01-15', 
 '2018-08-24', '2019-07-31', 'BJ',  
 '911007', 'SCHK', 'FVM', 
 'V&M TVA-INTELLECTUAL PROPERTY VAL', 'FAS', '',
 234000.00, 'EL16HKFAS0081', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-055', '1000055', 'CC055', 'MIC001-055', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'Creditors Voluntary', 'Referred by JSG (Japanese Services Group)', 'No',
 '314060', 'SHCA162-Project Avus&Libra(Success Fee)','2019-01-15', 
 '2018-08-24', '2019-07-31', 'NJ',  
 '911007', 'SCHK', 'FVM', 
 'V&M LCV-LITIGATION & CONTENTIOUS VAL', 'FAS', '',
 234000.00, 'EL16HKFAS0081', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-056', '1000056', 'CC056', 'MIC001-056', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'Court Liquidation', 'Client referral', 'No',
 '314060', 'BXCA161-FUND RAISING- Success fee','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'FVM', 
 'V&M MDL-STRA VAL & FIN MDL', 'FAS', '',
 234000.00, 'EL16HKFAS0081', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-057', '1000057', 'CC057', 'MIC001-057', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'Zhaoheng', 'Client referral', 'No',
 '314060', 'SHRA161-Liquidation advisory','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'FVM', 
 'V&M CAA-CAPITAL ASSET ADVISORY', 'FAS', '',
 234000.00, 'EL16HKFAS0081', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-058', '1000058', 'CC058', 'MIC001-058', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'Solid Life Limited', 'Internal development', 'No',
 '314060', 'SHCT171-Project Crystal- FDD&TDD','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'FVM', 
 'V&M MDL-PPP/I&CP ADVISORY', 'FAS', '',
 234000.00, 'EL16HKFAS0081', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')

INSERT INTO tr_project(id, DEL_FLAG, TENANT_ID,cea_no, client_code, client_name,engagement_code, contract_c, fisy,mic, pic, isSoe,
pic_name, mic_name, opportunity_id,
opportunity_name,opportunity_source, is_contingent_basis,
profit_ctr, engagement_desc, open_code_date,
start_date, close_date, location,
lcsp, region_code, service_offering,
service_offering_desc, func_service_line, scope_of_service,
est_Fee, eng_letter_no, is_recurring,engagement_risk,
confidentiality_risk, industry_code, industry,dtt_relationship,
client_risk, type_of_client, nature_of_business,
master_code, cea_status, service_item_team_member,
cea_approval_date, primary_address, city,
year_end_month,business_registration_no, country, province)
	VALUES(NEWID(), 0, 'FA', '021-059', '1000059', 'CC059', 'MIC001-059', 'US', '2020', '100517', '101094', 'true',
	'Tianyi', 'Ransheng', '3000001017', 
 'Fund raising', 'Existing client', 'No',
 '314060', 'BXRA171-BJ Master-retainer','2019-01-15', 
 '2018-08-24', '2019-07-31', 'HK',  
 '911007', 'SCHK', 'FVM', 
 'V&M RCV-AUDIT REVIEW SUPPORT', 'FAS', '',
 234000.00, 'EL16HKFAS0081', 'Y',
 'Normal', '', 'FZZ0', 
 'Financial Services Industry', 'No', 'Normal', 
 'Corporation', 'Private Equity', '1000010-0009-00-00-A01',
 'Approved', '','2017-03-18',
 '19th Floor, Room 1906-10,', NULL, '05', 
 '17876579-000', 'HK', 'HK')
