server:
  port: 8888
spring:
  application:
    name: demo
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull
    username: root
  data:
    mongodb:
      uri: mongodb://localhost:27017/RECOVERY
logging:
  level:
    root: INFO
ribbon:
  client:
    name: test