server:
  port: 8888
spring:
  application:
    name: demo
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.67.106/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull
    username: root
logging:
  level:
    root: DEBUG